//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VehicleEntities2 : DbContext
    {
        public VehicleEntities2()
            : base("name=VehicleEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Locat> Locats { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<returned> returneds { get; set; }
        public virtual DbSet<Sold> Solds { get; set; }
        public virtual DbSet<Tracker> Trackers { get; set; }
        public virtual DbSet<Trackertype> Trackertypes { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
    }
}
