//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sold
    {
        public int SaleID { get; set; }
        public Nullable<int> TrackerID { get; set; }
        public Nullable<int> LocID { get; set; }
        public Nullable<int> AppID { get; set; }
        public string Validate { get; set; }
    
        public virtual Locat Locat { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual Tracker Tracker { get; set; }
    }
}
