//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tracker()
        {
            this.Promotions = new HashSet<Promotion>();
            this.Solds = new HashSet<Sold>();
            this.Trackertypes = new HashSet<Trackertype>();
        }
    
        public int TrackerID { get; set; }
        public string Statuss { get; set; }
        public string Details { get; set; }
        public Nullable<int> Sales { get; set; }
        public string Validate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promotion> Promotions { get; set; }
        public virtual returned returned { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sold> Solds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trackertype> Trackertypes { get; set; }
    }
}
